### ISSUE TITLE
Breaking sliders.

### ISSUE THREAD

**Issue by thrashdin** [juhaku/loginized#14]
I cannot be 100% sure about this, but it seems, that after installing and changing background image, the sliders for sound/brightness from top right menu have vanished. I can still kinda move them, but they are invisible, as well as the line indicators. I can make a screenshot, if the description is too vague. 
I'd appreciate if we could investigate it a bit.

**Comment by juhaku** [comment]
Hello, that might happen due to the theme incompatibilities. Let me explain the process what happens when the image is changed. But first the of all everything that is shown in the login screen is coming from pre-compiled resource that contains images and css files. 

__The process when background image is changed__
1. Currently selected theme will be decompiled to resources.
2. Selected image will be copied to the resources.
3. The resources will be compiled.
4. The compiled archive will be used as system theme and placed under __/usr/share/themes/__

What happens here is that the theme changes completely. Even if the selected theme has the __gnome-shell.css__ file so that it suppose to support login screen theming. 
* It sill might not be fully implemented so that when the theme is used as login theme there appear to be glitches.
* Or the theme is outdated that it does not fully support the new gnome-shell version anymore.

How do I know what theme is being used. Well if you haven't selected any theme then it should be "Default". That default is the default theme shipped basically every gnome based distro. It's the blue adwaita. If that theme is used there should not be glitches. If any other theme is being used then any of above situations might be true. The oddball is the ubuntu though. It uses the default adwaita theme and overrides the colors to match to the it's color schema. This is atleast in the ubuntu 18.04. But there as well if the "Default" theme is used the above mentioned process will override this "Ubuntu hack" so it wont use the orange / purple flavored adwaita at all.

However if there are glitches when using the default theme. It might be that the version being used is outdated. The Loginized application caches the default theme on a first run or whatever theme that is being installed at __/usr/share/themes/gnome-shell-theme.gresource__. And it will always use that one if it exists and default theme is being selected from application. 
* You can update the default cached theme after system upgrade has changed your system's theme from the UI application settings view by dragging newly updated theme to the UI. You know when the system update changes the default theme is that your picture or theme has changed back to the default. This is when the __/usr/share/themes/gnome-shell-theme.gresource__ has changed.

Cheers
-Juha

**Comment by thrashdin** [comment]
I am using Debian 10 (latest stable, I guess). And I have "User theme" enabled in the gnome tweak tool. If I disable it, the sliders appear, but the lines are still invisible. 
So, are you saying that things can be randomly breaking and it would be too hard to deal with every theme?

**Comment by juhaku** [comment]
What I was trying to say is that the themes are not necesarily compatible to be used login theme. Which theme is selected for you in Loginized app? Default or some else?

Like in a nut shell the Loginized application does not have any magic inside. It basically only replaces the image from one file. So the glitches of invisible sliders or wrong colors or too narrow buttons and such is totally in the actual theme itself that is being used as a base. And those guys who make the themes should fix their themes.

I can do also some testing with debian 10 to see also how it behaves there. But I'm afraid that there is nothing that I am able fix in this manner.

**Comment by thrashdin** [comment]
I have actually tried about 10 different themes, for most of them, both
sliders and lines are broken, for some sliders work but the lines are
broken.
Atm I'm using a Arc-Orange (dark) for shell and Adwaita for everything
else. If I switch everything to default, sliders appear, but lines -- no.

Thank you anyway for reply, even if you don't have much time to investigate
this. I still appreciate the answer as well as the possibility to customize
debian default ugly loginscreen.

Andrew.

**Comment by juhaku** [comment]
I have made some changes to the application and now it suppose to extract the themes more precisely. Before the extraction was bit vague and that also might have been the reason for some of the issues. However with this latest version of the app things are better and I encourage to test it out. 

Thanks
-Juha

**Comment by sgnls** [comment]
I have the same issue; since installing and using Loginized to (successfully) change login GDM, I noticed invisible sliders for the volume OSD;

![image](https://user-images.githubusercontent.com/11134228/72686718-815a6080-3aef-11ea-8774-069a8d841546.png)

Issue persists across users and themes and that the symptoms I've experienced are the same as @thrashdin, evidently this is _triggered_, though but by not necessarily **caused**, by using Loginized.

The functionality remains and it's really not a critical problem, but this comment was to add weight to any uncertainty.

**GNOME Version :** 3.30.2 (Fedora)
**Loginized Version :** loginized-1.4.0.x86_64.rpm

For added context, this is what I was previously using to change the (default) background;

```
#!/bin/bash
gdmw(){

	path=/mnt/data/media/gdm
	img=$1

	cd /root/gnome-shell-js/
	mkdir -p ui/components ui/status misc perf extensionPrefs gdm theme

	gs=/usr/share/gnome-shell/gnome-shell-theme.gresource
	for r in `gresource list $gs`; do
		gresource extract $gs $r > ${r/#\/org\/gnome\/shell/.}
	done

	yes | cp -rf /usr/share/gnome-shell/gnome-shell-theme.gresource .
	touch gnome-shell-theme.gresource.xml
	echo '<?xml version="1.0" encoding="UTF-8"?>' >> gnome-shell-theme.gresource.xml
	echo "<gresources>" >> gnome-shell-theme.gresource.xml
	echo '<gresource prefix="/org/gnome/shell/theme">' >> gnome-shell-theme.gresource.xml
	gresource list gnome-shell-theme.gresource >> gnome-shell-theme.gresource.xml
	echo "</gresource>" >> gnome-shell-theme.gresource.xml
	echo "</gresources>" >> gnome-shell-theme.gresource.xml
	sed 's/\/org\/gnome\/shell\/theme\//\<file>/g' gnome-shell-theme.gresource.xml > gnome-1.xml
	sed 's/.svg/.svg\<\/file>/g' gnome-1.xml > gnome-2.xml
	sed 's/.png/.png\<\/file>/g' gnome-2.xml > gnome-1.xml
	sed 's/.css/.css\<\/file>/g' gnome-1.xml > gnome-shell-theme.gresource.xml
	rm -rfv gnome-[1-2].xml

	sed -e 's/noise-texture/$i/g' gnome-shell-theme.gresource.xml > gnome-shell-theme.gresource.xml.b && mv gnome-shell-theme.gresource.xml.b gnome-shell-theme.gresource.xml
	mv -fv gnome-shell-theme.gresource.xml theme && cd theme
	sed -e 's/noise-texture/$i/g' gnome-shell.css > gnome-shell.css.b && mv gnome-shell.css.b gnome-shell.css

	yes | cp -rf $path/$img $PWD
	glib-compile-resources gnome-shell-theme.gresource.xml
	cd /usr/share/gnome-shell
	mv -vf gnome-shell-theme.gresource gnome-shell-theme.gresource.bu
	yes | cp -rf $HOME/gnome-shell-js/theme/gnome-shell-theme.gresource .

}
gdmw $1
```
